/* 회원 정보 */
DROP TABLE MEMBER 
	CASCADE CONSTRAINTS;

/* 회원 구분 */
DROP TABLE MEMBER_CLASS 
	CASCADE CONSTRAINTS;

/* 쪽지 */
DROP TABLE MESSAGE 
	CASCADE CONSTRAINTS;

/* 주소록 */
DROP TABLE ADDR_BOOK 
	CASCADE CONSTRAINTS;

/* 디자인 의뢰서 */
DROP TABLE REQUEST 
	CASCADE CONSTRAINTS;

/* 공지사항 */
DROP TABLE NOTICE 
	CASCADE CONSTRAINTS;

/* 이미지 */
DROP TABLE TABLE7 
	CASCADE CONSTRAINTS;

/* 이미지 */
DROP TABLE TABLE8 
	CASCADE CONSTRAINTS;

/* 주문서 */
DROP TABLE ORDER 
	CASCADE CONSTRAINTS;

/* 주문 상태 */
DROP TABLE ORDER_STATE 
	CASCADE CONSTRAINTS;

/* 상품 */
DROP TABLE TABLE11 
	CASCADE CONSTRAINTS;

/* 새 테이블 */
DROP TABLE TABLE12 
	CASCADE CONSTRAINTS;

/* 부품 */
DROP TABLE TABLE13 
	CASCADE CONSTRAINTS;

/* 부품 판매 게시글 */
DROP TABLE PART 
	CASCADE CONSTRAINTS;

/* 디자인 제공 게시글 */
DROP TABLE DESIGN 
	CASCADE CONSTRAINTS;

/* 부품 묶음 */
DROP TABLE PART_SET 
	CASCADE CONSTRAINTS;

/* 완제품 */
DROP TABLE TABLE17 
	CASCADE CONSTRAINTS;

/* 상품 */
DROP TABLE TABLE18 
	CASCADE CONSTRAINTS;

/* 카테고리 */
DROP TABLE TABLE19 
	CASCADE CONSTRAINTS;

/* 카테고리 */
DROP TABLE CATEGORY 
	CASCADE CONSTRAINTS;

/* 디자인 카테고리 */
DROP TABLE TABLE21 
	CASCADE CONSTRAINTS;

/* Q&A */
DROP TABLE QA 
	CASCADE CONSTRAINTS;

/* 상품 */
DROP TABLE PRODUCT 
	CASCADE CONSTRAINTS;

/* 상품 1 */
DROP TABLE TABLE24 
	CASCADE CONSTRAINTS;

/* 상품  */
DROP TABLE TABLE25 
	CASCADE CONSTRAINTS;

/* 상품 2 */
DROP TABLE TABLE26 
	CASCADE CONSTRAINTS;

/* 상품 3 */
DROP TABLE TABLE27 
	CASCADE CONSTRAINTS;

/* FAQ */
DROP TABLE TABLE28 
	CASCADE CONSTRAINTS;

/* FAQ */
DROP TABLE FAQ 
	CASCADE CONSTRAINTS;

/* 배송 */
DROP TABLE TABLE30 
	CASCADE CONSTRAINTS;

/* 새 테이블2 */
DROP TABLE TABLE31 
	CASCADE CONSTRAINTS;

/* 카테고리 관계 */
DROP TABLE CATEGORY_RELATION 
	CASCADE CONSTRAINTS;

/* 배송 업체 */
DROP TABLE TABLE33 
	CASCADE CONSTRAINTS;

/* 배송 업체 */
DROP TABLE SHIP_COMPANY 
	CASCADE CONSTRAINTS;

/* 새 테이블3 */
DROP TABLE TABLE35 
	CASCADE CONSTRAINTS;

/* 회원 정보 */
CREATE TABLE MEMBER (
	MEMBER_ID VARCHAR2(30) NOT NULL, /* 아이디 */
	MEMBER_CLASS_CODE VARCHAR2(2) NOT NULL, /* 구분 코드 */
	MEMBER_PASSWORD VARCHAR2(30) NOT NULL, /* 비밀번호 */
	MEMBER_NAME VARCHAR2(30) NOT NULL, /* 이름 */
	MEMBER_BIRTHDAY DATE NOT NULL, /* 생년월일 */
	MEMBER_EMAIL VARCHAR2(30) NOT NULL, /* 이메일 */
	MEMBER_PHONE VARCHAR2(30) NOT NULL, /* 전화번호 */
	MEMBER_ADDRESS VARCHAR2(50) NOT NULL, /* 주소 */
	MEMBER_SIGN_DATE DATE NOT NULL, /* 가입일 */
	MEMBER_PROFILE_IMG VARCHAR2(50), /* 프로필 이미지 */
	MEMBER_POINT NUMBER NOT NULL, /* 포인트 */
	MEMBER_NICKNAME VARCHAR2(30) NOT NULL /* 별명 */
);

COMMENT ON TABLE MEMBER IS '회원 정보';

COMMENT ON COLUMN MEMBER.MEMBER_ID IS '아이디';

COMMENT ON COLUMN MEMBER.MEMBER_CLASS_CODE IS '구분 코드';

COMMENT ON COLUMN MEMBER.MEMBER_PASSWORD IS '비밀번호';

COMMENT ON COLUMN MEMBER.MEMBER_NAME IS '이름';

COMMENT ON COLUMN MEMBER.MEMBER_BIRTHDAY IS '생년월일';

COMMENT ON COLUMN MEMBER.MEMBER_EMAIL IS '이메일';

COMMENT ON COLUMN MEMBER.MEMBER_PHONE IS '전화번호';

COMMENT ON COLUMN MEMBER.MEMBER_ADDRESS IS '주소';

COMMENT ON COLUMN MEMBER.MEMBER_SIGN_DATE IS '가입일';

COMMENT ON COLUMN MEMBER.MEMBER_PROFILE_IMG IS '프로필 이미지';

COMMENT ON COLUMN MEMBER.MEMBER_POINT IS '누적 포인트';

COMMENT ON COLUMN MEMBER.MEMBER_NICKNAME IS '별명';

CREATE UNIQUE INDEX PK_MEMBER
	ON MEMBER (
		MEMBER_ID ASC
	);

ALTER TABLE MEMBER
	ADD
		CONSTRAINT PK_MEMBER
		PRIMARY KEY (
			MEMBER_ID
		);

/* 회원 구분 */
CREATE TABLE MEMBER_CLASS (
	MEMBER_CLASS_CODE VARCHAR2(2) NOT NULL, /* 구분 코드 */
	MEMBER_CLASS_NAME VARCHAR(20) NOT NULL /* 구분 명칭 */
);

COMMENT ON TABLE MEMBER_CLASS IS '회원 구분';

COMMENT ON COLUMN MEMBER_CLASS.MEMBER_CLASS_CODE IS '구분 코드';

COMMENT ON COLUMN MEMBER_CLASS.MEMBER_CLASS_NAME IS '구분 명칭';

CREATE UNIQUE INDEX PK_MEMBER_CLASS
	ON MEMBER_CLASS (
		MEMBER_CLASS_CODE ASC
	);

ALTER TABLE MEMBER_CLASS
	ADD
		CONSTRAINT PK_MEMBER_CLASS
		PRIMARY KEY (
			MEMBER_CLASS_CODE
		);

/* 쪽지 */
CREATE TABLE MESSAGE (
	MESSAGE_CODE VARCHAR2(10) NOT NULL, /* 쪽지 코드 */
	MESSAGE_SENDER_ID VARCHAR2(30) NOT NULL, /* 보낸 아이디 */
	MESSAGE_RECIPIENT_ID VARCHAR2(30) NOT NULL, /* 받는 아이디 */
	MESSAGE_CONTENTS VARCHAR2(500) NOT NULL, /* 내용 */
	MESSAGE_DATE DATE NOT NULL /* 작성일 */
);

COMMENT ON TABLE MESSAGE IS '쪽지';

COMMENT ON COLUMN MESSAGE.MESSAGE_CODE IS '쪽지 코드';

COMMENT ON COLUMN MESSAGE.MESSAGE_SENDER_ID IS '보낸 아이디';

COMMENT ON COLUMN MESSAGE.MESSAGE_RECIPIENT_ID IS '받는 아이디';

COMMENT ON COLUMN MESSAGE.MESSAGE_CONTENTS IS '내용';

COMMENT ON COLUMN MESSAGE.MESSAGE_DATE IS '작성일';

CREATE UNIQUE INDEX PK_MESSAGE
	ON MESSAGE (
		MESSAGE_CODE ASC
	);

ALTER TABLE MESSAGE
	ADD
		CONSTRAINT PK_MESSAGE
		PRIMARY KEY (
			MESSAGE_CODE
		);

/* 주소록 */
CREATE TABLE ADDR_BOOK (
	ADDR_BOOK_NAME VARCHAR2(30) NOT NULL, /* 주소록 명칭 */
	MEMBER_ID VARCHAR2(30) NOT NULL, /* 아이디 */
	ADDR_BOOK_ADDR VARCHAR2(50) NOT NULL, /* 주소 */
	ADDR_BOOK_POST VARCHAR2(30) NOT NULL, /* 우편 번호 */
	ADDR_BOOK_RECIPIENT VARCHAR2(30) NOT NULL, /* 받는이 */
	ADDR_BOOK_PHONE VARCHAR2(30) NOT NULL /* 전화번호 */
);

COMMENT ON TABLE ADDR_BOOK IS '주소록';

COMMENT ON COLUMN ADDR_BOOK.ADDR_BOOK_NAME IS '주소록 명칭';

COMMENT ON COLUMN ADDR_BOOK.MEMBER_ID IS '아이디';

COMMENT ON COLUMN ADDR_BOOK.ADDR_BOOK_ADDR IS '주소';

COMMENT ON COLUMN ADDR_BOOK.ADDR_BOOK_POST IS '우편 번호';

COMMENT ON COLUMN ADDR_BOOK.ADDR_BOOK_RECIPIENT IS '받는이';

COMMENT ON COLUMN ADDR_BOOK.ADDR_BOOK_PHONE IS '전화번호';

CREATE UNIQUE INDEX PK_ADDR_BOOK
	ON ADDR_BOOK (
		ADDR_BOOK_NAME ASC
	);

ALTER TABLE ADDR_BOOK
	ADD
		CONSTRAINT PK_ADDR_BOOK
		PRIMARY KEY (
			ADDR_BOOK_NAME
		);

/* 디자인 의뢰서 */
CREATE TABLE REQUEST (
	REQUEST_CODE VARCHAR2(10) NOT NULL, /* 의뢰서 코드 */
	MEMBER_ID VARCHAR2(30), /* 아이디 */
	REQUEST_TITLE <지정 되지 않음>, /* 제목 */
	REQUEST_DATE DATE NOT NULL, /* 작성일 */
	REQUEST_CONTENTS VARCHAR2(500) NOT NULL, /* 내용 */
	REQUEST_FILE VARCHAR2(50) NOT NULL /* 첨부 파일 */
);

COMMENT ON TABLE REQUEST IS '디자인 의뢰서';

COMMENT ON COLUMN REQUEST.REQUEST_CODE IS '의뢰서 코드';

COMMENT ON COLUMN REQUEST.MEMBER_ID IS '아이디';

COMMENT ON COLUMN REQUEST.REQUEST_TITLE IS '제목';

COMMENT ON COLUMN REQUEST.REQUEST_DATE IS '작성일';

COMMENT ON COLUMN REQUEST.REQUEST_CONTENTS IS '내용';

COMMENT ON COLUMN REQUEST.REQUEST_FILE IS '첨부 파일';

CREATE UNIQUE INDEX PK_REQUEST
	ON REQUEST (
		REQUEST_CODE ASC
	);

ALTER TABLE REQUEST
	ADD
		CONSTRAINT PK_REQUEST
		PRIMARY KEY (
			REQUEST_CODE
		);

/* 공지사항 */
CREATE TABLE NOTICE (
	NOTICE_CODE VARCHAR2(10) NOT NULL, /* 공지사항 코드 */
	NOTICE_TITLE VARCHAR2(50) NOT NULL, /* 제목 */
	NOTICE_CONTENTS VARCHAR2(500) NOT NULL, /* 내용 */
	NOTICE_DATE DATE NOT NULL, /* 작성일 */
	NOTICE_IMG VARCHAR2(50) /* 이미지 */
);

COMMENT ON TABLE NOTICE IS '공지사항';

COMMENT ON COLUMN NOTICE.NOTICE_CODE IS '공지사항 코드';

COMMENT ON COLUMN NOTICE.NOTICE_TITLE IS '제목';

COMMENT ON COLUMN NOTICE.NOTICE_CONTENTS IS '내용';

COMMENT ON COLUMN NOTICE.NOTICE_DATE IS '작성일';

COMMENT ON COLUMN NOTICE.NOTICE_IMG IS '이미지';

CREATE UNIQUE INDEX PK_NOTICE
	ON NOTICE (
		NOTICE_CODE ASC
	);

ALTER TABLE NOTICE
	ADD
		CONSTRAINT PK_NOTICE
		PRIMARY KEY (
			NOTICE_CODE
		);

/* 이미지 */
CREATE TABLE TABLE7 (
	COL <지정 되지 않음>, /* 게시글 코드 */
	COL2 <지정 되지 않음>, /* 서버의 이미지 주소 */
	REQUEST_CODE VARCHAR2(10), /* 의뢰서 코드 */
	NOTICE_CODE VARCHAR2(10) /* 공지사항 코드 */
);

COMMENT ON TABLE TABLE7 IS '이미지';

COMMENT ON COLUMN TABLE7.COL IS '게시글 코드';

COMMENT ON COLUMN TABLE7.COL2 IS '서버의 이미지 주소';

COMMENT ON COLUMN TABLE7.REQUEST_CODE IS '의뢰서 코드';

COMMENT ON COLUMN TABLE7.NOTICE_CODE IS '공지사항 코드';

/* 이미지 */
CREATE TABLE TABLE8 (
);

COMMENT ON TABLE TABLE8 IS '이미지';

/* 주문서 */
CREATE TABLE ORDER (
	ORDER_CODE VARCHAR2(10) NOT NULL, /* 주문 코드 */
	MEMBER_ID VARCHAR2(30) NOT NULL, /* 아이디 */
	ORDER_DATE DATE NOT NULL, /* 주문일 */
	ORDER_POINT NUMBER, /* 주문별 포인트 */
	ORDER_STATE_CODE VARCHAR2(10) NOT NULL, /* 상태 코드 */
	SHIP_COMPANY_NAME VARCHAR2(30), /* 배송 업체명 */
	ORDER_SHIP_CODE VARCHAR2(30) /* 운송장 번호 */
);

COMMENT ON TABLE ORDER IS '주문서';

COMMENT ON COLUMN ORDER.ORDER_CODE IS '주문 코드';

COMMENT ON COLUMN ORDER.MEMBER_ID IS '아이디';

COMMENT ON COLUMN ORDER.ORDER_DATE IS '주문일';

COMMENT ON COLUMN ORDER.ORDER_POINT IS '주문별 포인트';

COMMENT ON COLUMN ORDER.ORDER_STATE_CODE IS '상태 코드';

COMMENT ON COLUMN ORDER.SHIP_COMPANY_NAME IS '배송 업체명';

COMMENT ON COLUMN ORDER.ORDER_SHIP_CODE IS '운송장 번호';

CREATE UNIQUE INDEX PK_ORDER
	ON ORDER (
		ORDER_CODE ASC
	);

ALTER TABLE ORDER
	ADD
		CONSTRAINT PK_ORDER
		PRIMARY KEY (
			ORDER_CODE
		);

/* 주문 상태 */
CREATE TABLE ORDER_STATE (
	ORDER_STATE_CODE VARCHAR2(10) NOT NULL, /* 상태 코드 */
	ORDER_STATE_NAME VARCHAR2(30) NOT NULL /* 상태 명칭 */
);

COMMENT ON TABLE ORDER_STATE IS '주문 상태';

COMMENT ON COLUMN ORDER_STATE.ORDER_STATE_CODE IS '상태 코드';

COMMENT ON COLUMN ORDER_STATE.ORDER_STATE_NAME IS '상태 명칭';

CREATE UNIQUE INDEX PK_ORDER_STATE
	ON ORDER_STATE (
		ORDER_STATE_CODE ASC
	);

ALTER TABLE ORDER_STATE
	ADD
		CONSTRAINT PK_ORDER_STATE
		PRIMARY KEY (
			ORDER_STATE_CODE
		);

/* 상품 */
CREATE TABLE TABLE11 (
	COL <지정 되지 않음> NOT NULL /* 상품 코드 */
);

COMMENT ON TABLE TABLE11 IS '상품';

COMMENT ON COLUMN TABLE11.COL IS '상품 코드';

CREATE UNIQUE INDEX PK_TABLE11
	ON TABLE11 (
		COL ASC
	);

ALTER TABLE TABLE11
	ADD
		CONSTRAINT PK_TABLE11
		PRIMARY KEY (
			COL
		);

/* 새 테이블 */
CREATE TABLE TABLE12 (
);

COMMENT ON TABLE TABLE12 IS '새 테이블';

/* 부품 */
CREATE TABLE TABLE13 (
	PART_CODE VARCHAR2(10) NOT NULL, /* 부품 코드 */
	PART_NAME VARCHAR2(30) NOT NULL, /* 부품 명칭 */
	PART_PRICE NUMBER NOT NULL, /* 가격 */
	PART_STOCK NUMBER NOT NULL /* 재고 */
);

COMMENT ON TABLE TABLE13 IS '부품';

COMMENT ON COLUMN TABLE13.PART_CODE IS '부품 코드';

COMMENT ON COLUMN TABLE13.PART_NAME IS '부품 명칭';

COMMENT ON COLUMN TABLE13.PART_PRICE IS '가격';

COMMENT ON COLUMN TABLE13.PART_STOCK IS '재고';

CREATE UNIQUE INDEX PK_TABLE13
	ON TABLE13 (
		PART_CODE ASC
	);

ALTER TABLE TABLE13
	ADD
		CONSTRAINT PK_TABLE13
		PRIMARY KEY (
			PART_CODE
		);

/* 부품 판매 게시글 */
CREATE TABLE PART (
	PART_CODE VARCHAR2(10) NOT NULL, /* 부품 코드 */
	PART_TITLE VARCHAR2(50) NOT NULL, /* 제목(부품 명칭) */
	PART_DATE DATE NOT NULL, /* 작성일 */
	PART_PRICE NUMBER NOT NULL, /* 가격 */
	PART_STOCK NUMBER NOT NULL, /* 재고 */
	PART_CONTENTS VARCHAR2(500) NOT NULL, /* 내용 */
	PART_IMG VARCHAR2(50) NOT NULL /* 이미지 */
);

COMMENT ON TABLE PART IS '부품 판매 게시글';

COMMENT ON COLUMN PART.PART_CODE IS '부품 코드';

COMMENT ON COLUMN PART.PART_TITLE IS '제목(부품 명칭)';

COMMENT ON COLUMN PART.PART_DATE IS '작성일';

COMMENT ON COLUMN PART.PART_PRICE IS '가격';

COMMENT ON COLUMN PART.PART_STOCK IS '재고';

COMMENT ON COLUMN PART.PART_CONTENTS IS '내용';

COMMENT ON COLUMN PART.PART_IMG IS '이미지';

CREATE UNIQUE INDEX PK_PART
	ON PART (
		PART_CODE ASC
	);

ALTER TABLE PART
	ADD
		CONSTRAINT PK_PART
		PRIMARY KEY (
			PART_CODE
		);

/* 디자인 제공 게시글 */
CREATE TABLE DESIGN (
	DESIGN_CODE VARCHAR2(10) NOT NULL, /* 디자인 코드 */
	DESIGN_TITLE VARCHAR2(50) NOT NULL, /* 제목 */
	DESIGN_DATE DATE NOT NULL, /* 작성일 */
	DESIGN_CONTENTS VARCHAR2(500) NOT NULL, /* 내용 */
	DESIGN_PRICE NUMBER NOT NULL, /* 가격 */
	DESIGN_IMG VARCHAR2(50) NOT NULL, /* 이미지 */
	MEMBER_ID VARCHAR2(30) /* 디자이너 */
);

COMMENT ON TABLE DESIGN IS '디자인 제공 게시글';

COMMENT ON COLUMN DESIGN.DESIGN_CODE IS '디자인 코드';

COMMENT ON COLUMN DESIGN.DESIGN_TITLE IS '제목';

COMMENT ON COLUMN DESIGN.DESIGN_DATE IS '작성일';

COMMENT ON COLUMN DESIGN.DESIGN_CONTENTS IS '내용';

COMMENT ON COLUMN DESIGN.DESIGN_PRICE IS '가격';

COMMENT ON COLUMN DESIGN.DESIGN_IMG IS '이미지';

COMMENT ON COLUMN DESIGN.MEMBER_ID IS '디자이너';

CREATE UNIQUE INDEX PK_DESIGN
	ON DESIGN (
		DESIGN_CODE ASC
	);

ALTER TABLE DESIGN
	ADD
		CONSTRAINT PK_DESIGN
		PRIMARY KEY (
			DESIGN_CODE
		);

/* 부품 묶음 */
CREATE TABLE PART_SET (
	DESIGN_CODE VARCHAR2(10) NOT NULL, /* 디자인 코드 */
	PART_CODE VARCHAR2(10) NOT NULL /* 부품 코드 */
);

COMMENT ON TABLE PART_SET IS '부품 묶음';

COMMENT ON COLUMN PART_SET.DESIGN_CODE IS '디자인 코드';

COMMENT ON COLUMN PART_SET.PART_CODE IS '부품 코드';

/* 완제품 */
CREATE TABLE TABLE17 (
	COL VARCHAR2(10) NOT NULL, /* 완제품 코드 */
	COL2 <지정 되지 않음> NOT NULL /* 가격 */
);

COMMENT ON TABLE TABLE17 IS '완제품';

COMMENT ON COLUMN TABLE17.COL IS '완제품 코드';

COMMENT ON COLUMN TABLE17.COL2 IS '가격';

CREATE UNIQUE INDEX PK_TABLE17
	ON TABLE17 (
		COL ASC
	);

ALTER TABLE TABLE17
	ADD
		CONSTRAINT PK_TABLE17
		PRIMARY KEY (
			COL
		);

/* 상품 */
CREATE TABLE TABLE18 (
);

COMMENT ON TABLE TABLE18 IS '상품';

/* 카테고리 */
CREATE TABLE TABLE19 (
	COL <지정 되지 않음> NOT NULL, /* 카테고리 코드 */
	COL2 <지정 되지 않음> NOT NULL /* 카테고리 명칭 */
);

COMMENT ON TABLE TABLE19 IS '카테고리';

COMMENT ON COLUMN TABLE19.COL IS '카테고리 코드';

COMMENT ON COLUMN TABLE19.COL2 IS '카테고리 명칭';

CREATE UNIQUE INDEX PK_TABLE19
	ON TABLE19 (
		COL ASC
	);

ALTER TABLE TABLE19
	ADD
		CONSTRAINT PK_TABLE19
		PRIMARY KEY (
			COL
		);

/* 카테고리 */
CREATE TABLE CATEGORY (
	CATEGORY_CODE VARCHAR2(10) NOT NULL, /* 카테고리 코드 */
	CATEGORY_NAME VARCHAR2(30) NOT NULL /* 카테고리 명칭 */
);

COMMENT ON TABLE CATEGORY IS '카테고리';

COMMENT ON COLUMN CATEGORY.CATEGORY_CODE IS '카테고리 코드';

COMMENT ON COLUMN CATEGORY.CATEGORY_NAME IS '카테고리 명칭';

CREATE UNIQUE INDEX PK_CATEGORY
	ON CATEGORY (
		CATEGORY_CODE ASC
	);

ALTER TABLE CATEGORY
	ADD
		CONSTRAINT PK_CATEGORY
		PRIMARY KEY (
			CATEGORY_CODE
		);

/* 디자인 카테고리 */
CREATE TABLE TABLE21 (
	DESIGN_CODE VARCHAR2(10) NOT NULL, /* 디자인 코드 */
	COL2 <지정 되지 않음> NOT NULL /* 카테고리 코드 */
);

COMMENT ON TABLE TABLE21 IS '디자인 카테고리';

COMMENT ON COLUMN TABLE21.DESIGN_CODE IS '디자인 코드';

COMMENT ON COLUMN TABLE21.COL2 IS '카테고리 코드';

/* Q&A */
CREATE TABLE QA (
	QA_CODE VARCHAR2(10) NOT NULL, /* 공지사항 코드 */
	MEMBER_ID VARCHAR2(30) NOT NULL, /* 아이디 */
	QA_TITLE VARCHAR2(50) NOT NULL, /* 제목 */
	QA_CONTENTS VARCHAR2(500) NOT NULL, /* 내용 */
	QA_DATE DATE NOT NULL, /* 작성일 */
	QA_IMG VARCHAR2(50), /* 이미지 */
	QA_ANSWER VARCHAR2(500) /* 답변 */
);

COMMENT ON TABLE QA IS 'Q&A';

COMMENT ON COLUMN QA.QA_CODE IS '공지사항 코드';

COMMENT ON COLUMN QA.MEMBER_ID IS '아이디';

COMMENT ON COLUMN QA.QA_TITLE IS '제목';

COMMENT ON COLUMN QA.QA_CONTENTS IS '내용';

COMMENT ON COLUMN QA.QA_DATE IS '작성일';

COMMENT ON COLUMN QA.QA_IMG IS '이미지';

COMMENT ON COLUMN QA.QA_ANSWER IS '답변';

CREATE UNIQUE INDEX PK_QA
	ON QA (
		QA_CODE ASC
	);

ALTER TABLE QA
	ADD
		CONSTRAINT PK_QA
		PRIMARY KEY (
			QA_CODE
		);

/* 상품 */
CREATE TABLE PRODUCT (
	ORDER_CODE VARCHAR2(10) NOT NULL, /* 주문 코드 */
	DESIGN_CODE VARCHAR2(10), /* 디자인 코드 */
	PART_CODE VARCHAR2(10) /* 부품 코드 */
);

COMMENT ON TABLE PRODUCT IS '상품';

COMMENT ON COLUMN PRODUCT.ORDER_CODE IS '주문 코드';

COMMENT ON COLUMN PRODUCT.DESIGN_CODE IS '디자인 코드';

COMMENT ON COLUMN PRODUCT.PART_CODE IS '부품 코드';

/* 상품 1 */
CREATE TABLE TABLE24 (
	COL3 <지정 되지 않음> NOT NULL, /* 123 */
	PART_CODE VARCHAR2(10) /* 부품 코드 */
);

COMMENT ON TABLE TABLE24 IS '상품 1';

COMMENT ON COLUMN TABLE24.COL3 IS '123';

COMMENT ON COLUMN TABLE24.PART_CODE IS '부품 코드';

CREATE UNIQUE INDEX PK_TABLE24
	ON TABLE24 (
		COL3 ASC
	);

ALTER TABLE TABLE24
	ADD
		CONSTRAINT PK_TABLE24
		PRIMARY KEY (
			COL3
		);

/* 상품  */
CREATE TABLE TABLE25 (
);

COMMENT ON TABLE TABLE25 IS '상품 ';

/* 상품 2 */
CREATE TABLE TABLE26 (
	COL3 <지정 되지 않음> NOT NULL /* 123 */
);

COMMENT ON TABLE TABLE26 IS '상품 2';

COMMENT ON COLUMN TABLE26.COL3 IS '123';

CREATE UNIQUE INDEX PK_TABLE26
	ON TABLE26 (
		COL3 ASC
	);

ALTER TABLE TABLE26
	ADD
		CONSTRAINT PK_TABLE26
		PRIMARY KEY (
			COL3
		);

/* 상품 3 */
CREATE TABLE TABLE27 (
	COL3 <지정 되지 않음> NOT NULL /* 123 */
);

COMMENT ON TABLE TABLE27 IS '상품 3';

COMMENT ON COLUMN TABLE27.COL3 IS '123';

CREATE UNIQUE INDEX PK_TABLE27
	ON TABLE27 (
		COL3 ASC
	);

ALTER TABLE TABLE27
	ADD
		CONSTRAINT PK_TABLE27
		PRIMARY KEY (
			COL3
		);

/* FAQ */
CREATE TABLE TABLE28 (
);

COMMENT ON TABLE TABLE28 IS 'FAQ';

/* FAQ */
CREATE TABLE FAQ (
	FAQ_CODE VARCHAR2(10) NOT NULL, /* FAQ 코드 */
	FAQ_TITLE VARCHAR2(50) NOT NULL, /* 제목 */
	FAQ_CONTENT VARCHAR2(500 NOT NULL, /* 내용 */
	FAQ_CONTENTS DATE NOT NULL, /* 작성일 */
	FAQ_IMG VARCHAR2(50) /* 이미지 */
);

COMMENT ON TABLE FAQ IS 'FAQ';

COMMENT ON COLUMN FAQ.FAQ_CODE IS 'FAQ 코드';

COMMENT ON COLUMN FAQ.FAQ_TITLE IS '제목';

COMMENT ON COLUMN FAQ.FAQ_CONTENT IS '내용';

COMMENT ON COLUMN FAQ.FAQ_CONTENTS IS '작성일';

COMMENT ON COLUMN FAQ.FAQ_IMG IS '이미지';

CREATE UNIQUE INDEX PK_FAQ
	ON FAQ (
		FAQ_CODE ASC
	);

ALTER TABLE FAQ
	ADD
		CONSTRAINT PK_FAQ
		PRIMARY KEY (
			FAQ_CODE
		);

/* 배송 */
CREATE TABLE TABLE30 (
	SHIP_CODE <지정 되지 않음> NOT NULL, /* 새 컬럼 */
	ORDER_CODE VARCHAR2(10) /* 주문 코드 */
);

COMMENT ON TABLE TABLE30 IS '배송';

COMMENT ON COLUMN TABLE30.SHIP_CODE IS '새 컬럼';

COMMENT ON COLUMN TABLE30.ORDER_CODE IS '주문 코드';

CREATE UNIQUE INDEX PK_TABLE30
	ON TABLE30 (
		SHIP_CODE ASC
	);

ALTER TABLE TABLE30
	ADD
		CONSTRAINT PK_TABLE30
		PRIMARY KEY (
			SHIP_CODE
		);

/* 새 테이블2 */
CREATE TABLE TABLE31 (
);

COMMENT ON TABLE TABLE31 IS '새 테이블2';

/* 카테고리 관계 */
CREATE TABLE CATEGORY_RELATION (
	CATEGORY_CODE VARCHAR2(10) NOT NULL, /* 카테고리 코드 */
	DESIGN_CODE VARCHAR2(10), /* 디자인 코드 */
	PART_CODE VARCHAR2(10) /* 부품 코드 */
);

COMMENT ON TABLE CATEGORY_RELATION IS '카테고리 관계';

COMMENT ON COLUMN CATEGORY_RELATION.CATEGORY_CODE IS '카테고리 코드';

COMMENT ON COLUMN CATEGORY_RELATION.DESIGN_CODE IS '디자인 코드';

COMMENT ON COLUMN CATEGORY_RELATION.PART_CODE IS '부품 코드';

/* 배송 업체 */
CREATE TABLE TABLE33 (
	SHIP_COMPANY_NAME <지정 되지 않음>, /* 배송 업체 */
	SHIPCOMPANY_ <지정 되지 않음> /* 새 컬럼 */
);

COMMENT ON TABLE TABLE33 IS '배송 업체';

COMMENT ON COLUMN TABLE33.SHIP_COMPANY_NAME IS '배송 업체';

COMMENT ON COLUMN TABLE33.SHIPCOMPANY_ IS '새 컬럼';

/* 배송 업체 */
CREATE TABLE SHIP_COMPANY (
	SHIP_COMPANY_NAME VARCHAR2(30) NOT NULL, /* 배송 업체명 */
	SHIP_COMPANY_URL VARCHAR2(100) /* 배송 업체 URL */
);

COMMENT ON TABLE SHIP_COMPANY IS '배송 업체';

COMMENT ON COLUMN SHIP_COMPANY.SHIP_COMPANY_NAME IS '배송 업체명';

COMMENT ON COLUMN SHIP_COMPANY.SHIP_COMPANY_URL IS '배송 업체 URL';

CREATE UNIQUE INDEX PK_SHIP_COMPANY
	ON SHIP_COMPANY (
		SHIP_COMPANY_NAME ASC
	);

ALTER TABLE SHIP_COMPANY
	ADD
		CONSTRAINT PK_SHIP_COMPANY
		PRIMARY KEY (
			SHIP_COMPANY_NAME
		);

/* 새 테이블3 */
CREATE TABLE TABLE35 (
);

COMMENT ON TABLE TABLE35 IS '새 테이블3';

ALTER TABLE MEMBER
	ADD
		CONSTRAINT FK_MEMBER_CLASS_TO_MEMBER
		FOREIGN KEY (
			MEMBER_CLASS_CODE
		)
		REFERENCES MEMBER_CLASS (
			MEMBER_CLASS_CODE
		);

ALTER TABLE MESSAGE
	ADD
		CONSTRAINT FK_MEMBER_TO_MESSAGE
		FOREIGN KEY (
			MESSAGE_SENDER_ID
		)
		REFERENCES MEMBER (
			MEMBER_ID
		);

ALTER TABLE MESSAGE
	ADD
		CONSTRAINT FK_MEMBER_TO_MESSAGE2
		FOREIGN KEY (
			MESSAGE_RECIPIENT_ID
		)
		REFERENCES MEMBER (
			MEMBER_ID
		);

ALTER TABLE ADDR_BOOK
	ADD
		CONSTRAINT FK_MEMBER_TO_ADDR_BOOK
		FOREIGN KEY (
			MEMBER_ID
		)
		REFERENCES MEMBER (
			MEMBER_ID
		);

ALTER TABLE REQUEST
	ADD
		CONSTRAINT FK_MEMBER_TO_REQUEST
		FOREIGN KEY (
			MEMBER_ID
		)
		REFERENCES MEMBER (
			MEMBER_ID
		);

ALTER TABLE TABLE7
	ADD
		CONSTRAINT FK_REQUEST_TO_TABLE7
		FOREIGN KEY (
			REQUEST_CODE
		)
		REFERENCES REQUEST (
			REQUEST_CODE
		);

ALTER TABLE TABLE7
	ADD
		CONSTRAINT FK_NOTICE_TO_TABLE7
		FOREIGN KEY (
			NOTICE_CODE
		)
		REFERENCES NOTICE (
			NOTICE_CODE
		);

ALTER TABLE ORDER
	ADD
		CONSTRAINT FK_MEMBER_TO_ORDER
		FOREIGN KEY (
			MEMBER_ID
		)
		REFERENCES MEMBER (
			MEMBER_ID
		);

ALTER TABLE ORDER
	ADD
		CONSTRAINT FK_ORDER_STATE_TO_ORDER
		FOREIGN KEY (
			ORDER_STATE_CODE
		)
		REFERENCES ORDER_STATE (
			ORDER_STATE_CODE
		);

ALTER TABLE ORDER
	ADD
		CONSTRAINT FK_SHIP_COMPANY_TO_ORDER
		FOREIGN KEY (
			SHIP_COMPANY_NAME
		)
		REFERENCES SHIP_COMPANY (
			SHIP_COMPANY_NAME
		);

ALTER TABLE DESIGN
	ADD
		CONSTRAINT FK_MEMBER_TO_DESIGN
		FOREIGN KEY (
			MEMBER_ID
		)
		REFERENCES MEMBER (
			MEMBER_ID
		);

ALTER TABLE PART_SET
	ADD
		CONSTRAINT FK_DESIGN_TO_PART_SET
		FOREIGN KEY (
			DESIGN_CODE
		)
		REFERENCES DESIGN (
			DESIGN_CODE
		);

ALTER TABLE PART_SET
	ADD
		CONSTRAINT FK_PART_TO_PART_SET
		FOREIGN KEY (
			PART_CODE
		)
		REFERENCES PART (
			PART_CODE
		);

ALTER TABLE TABLE21
	ADD
		CONSTRAINT FK_DESIGN_TO_TABLE21
		FOREIGN KEY (
			DESIGN_CODE
		)
		REFERENCES DESIGN (
			DESIGN_CODE
		);

ALTER TABLE TABLE21
	ADD
		CONSTRAINT FK_TABLE19_TO_TABLE21
		FOREIGN KEY (
			COL2
		)
		REFERENCES TABLE19 (
			COL
		);

ALTER TABLE QA
	ADD
		CONSTRAINT FK_MEMBER_TO_QA
		FOREIGN KEY (
			MEMBER_ID
		)
		REFERENCES MEMBER (
			MEMBER_ID
		);

ALTER TABLE PRODUCT
	ADD
		CONSTRAINT FK_ORDER_TO_PRODUCT
		FOREIGN KEY (
			ORDER_CODE
		)
		REFERENCES ORDER (
			ORDER_CODE
		);

ALTER TABLE PRODUCT
	ADD
		CONSTRAINT FK_DESIGN_TO_PRODUCT
		FOREIGN KEY (
			DESIGN_CODE
		)
		REFERENCES DESIGN (
			DESIGN_CODE
		);

ALTER TABLE PRODUCT
	ADD
		CONSTRAINT FK_PART_TO_PRODUCT
		FOREIGN KEY (
			PART_CODE
		)
		REFERENCES PART (
			PART_CODE
		);

ALTER TABLE TABLE24
	ADD
		CONSTRAINT FK_TABLE13_TO_TABLE24
		FOREIGN KEY (
			PART_CODE
		)
		REFERENCES TABLE13 (
			PART_CODE
		);

ALTER TABLE TABLE30
	ADD
		CONSTRAINT FK_ORDER_TO_TABLE30
		FOREIGN KEY (
			ORDER_CODE
		)
		REFERENCES ORDER (
			ORDER_CODE
		);

ALTER TABLE CATEGORY_RELATION
	ADD
		CONSTRAINT FK_CATEGORY_TO_CATEGORY_RELATION
		FOREIGN KEY (
			CATEGORY_CODE
		)
		REFERENCES CATEGORY (
			CATEGORY_CODE
		);

ALTER TABLE CATEGORY_RELATION
	ADD
		CONSTRAINT FK_DESIGN_TO_CATEGORY_RELATION
		FOREIGN KEY (
			DESIGN_CODE
		)
		REFERENCES DESIGN (
			DESIGN_CODE
		);

ALTER TABLE CATEGORY_RELATION
	ADD
		CONSTRAINT FK_PART_TO_CATEGORY_RELATION
		FOREIGN KEY (
			PART_CODE
		)
		REFERENCES PART (
			PART_CODE
		);